### ISSUE TITLE
Dutch / Netherland

### ISSUE THREAD

**Issue by mtorulez** [ParisNeo/chatgpt-personality-selector#1]
add language Dutch / Netherlands

**Comment by ParisNeo** [comment]
OK. I'll try doing this

**Comment by ParisNeo** [comment]
I have started the translation process.
It should take some time. I may need some feedback to correct some translation errors as the translator is not perfect.

**Comment by ParisNeo** [comment]
I have added this translation to v1.9.
You can either recover it from the github repository or wait till google validate the update.
It shoudn't take too much time to be validated.

Best regards

**Comment by mtorulez** [comment]
Thank you!

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: Saifeddine ***@***.***>
Verzonden: donderdag 2 maart 2023 18:43
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [ParisNeo/chatgpt-personality-selector] Dutch / Netherland (Issue #1)


I have added this translation to v1.9.
You can either recover it from the github repository or wait till google validate the update.
It shoudn't take too much time to be validated.

Best regards
