### ISSUE TITLE
Can you support the Chinese language and Chinese text-to-speech?

### ISSUE THREAD

**Issue by alanjustalan** [ParisNeo/chatgpt-personality-selector#2]
The plugin you've written is really useful. It would be even better if it could support Chinese language and Chinese text-to-speech. Thanks~

**Comment by ParisNeo** [comment]
Hi, I'll do it :)

**Comment by ParisNeo** [comment]
Chinese is now supported since version 2.1.0
The version is submitted to google chrome, it should be live in few days.
