### ISSUE TITLE
Stopped accessing the internet

### ISSUE THREAD

**Issue by Herris23** [ParisNeo/chatgpt-personality-selector#3]
**Describe the bug**
Started not accessing the net. Gives the response 'As an AI language model..."

**To Reproduce**

Just access the page.

**Expected behavior**
No net access.

**Screenshots**

**Desktop (please complete the following information):**

Windows 10

**Smartphone (please complete the following information):**

**Additional context**
Uninstalled and reinstalled. Tried the code from GitHUB with the same result.

**Comment by ParisNeo** [comment]
I just tried it and it worked. It is getting heavy thoug but as I don't have enough money I am using a free server which reduces the amount of traffic it can handle. Sorry brow.

**Comment by Herris23** [comment]
Is the back end code on Github?

**Comment by Herris23** [comment]
Or can you tell me the format the data returned is? I will attempt to build one. Not sure what the backend does other than doing an api call. Looks like it returns href and body?

**Comment by Herris23** [comment]
Nevermind. I modified the code to use Google Custom Search api and added fields for the apikey and searchengine id. Seems to be working.
