### ISSUE TITLE
Misspellings in UI

### ISSUE THREAD

**Issue by ferula-P** [ParisNeo/chatgpt-personality-selector#4]
English teach me:
Philosophy is misspelled as phylosophy. 

English Games:
dungeons and dragons misspelling

English Generator
Pseudonym is misspelled.

Thanks for the tool by the way!

**Comment by ParisNeo** [comment]
Hi. Thank you for the information, I'll fix that.
I am non native english speaker :)

**Comment by ferula-P** [comment]
It's no problem, just figured I'd let you know!
